# Site settings
title: Lahumiere
email: ""
description: ""
baseurl: "lahumiere"
url: "http://rougerose.github.io"

# Build settings
markdown: kramdown

exclude:
  - package.json
  - node_modules
  - gulpfile.js
